SHOT_TYPES = [
    "cinematic candid moment",
    "confident full-body glamour pose",
    "over-the-shoulder pose",
    "close-up beauty portrait",
    "natural relaxed candid",
    "seated confident pose",
    "leaning casual pose",
    "sensual topless floor pose",
    "laying back on floor touching breasts",
    "hands squeezing breasts",
    "rubbing wet panties",
    "sliding panties off",
    "full nude legs spread on floor",
    "intimate self touch fingers on clit",
    "masturbating with fingers inside",
    "pleasure expression eyes closed",
    "arching back nude pose",
    "kneeling nude on floor",
    "wet glistening skin intimate moment",
]